### ISSUE TITLE
[RemoteDesktop] Added GNOME and Wayland RDP by Default

### ISSUE THREAD

**Issue by tmichett** [tmichett/Fedora_Remix#130]
Add Gnome and Wayland RDP to default (possibly through the Fedora Tools)

**Comment by tmichett** [comment]
grdctl rdp enable

**Comment by tmichett** [comment]
grdctl rdp disable-view-only

**Comment by tmichett** [comment]
systemctl --user enable --now gnome-remote-desktop.service

**Comment by tmichett** [comment]
grdctl rdp set-credentials <username> <password>

**Comment by tmichett** [comment]
Generate User Certs

export GRDCERTDIR=~/.rdp-certs
mkdir -p $GRDCERTDIR
openssl genrsa -out ${GRDCERTDIR}/grd-tls.key 4096
openssl req -new -key ${GRDCERTDIR}/grd-tls.key -out ${GRDCERTDIR}/grd-tls.csr -subj "/C=US/ST=State/L=City/O=Organization/OU=Unit/CN=$(hostname)"
openssl x509 -req -days 3650 -in ${GRDCERTDIR}/grd-tls.csr -signkey ${GRDCERTDIR}/grd-tls.key -out ${GRDCERTDIR}/grd-tls.crt
chmod 600 ${GRDCERTDIR}/grd-tls.key

**Comment by tmichett** [comment]
Configure Certs

grdctl rdp set-tls-cert ~/.rdp-certs/grd-tls.crt
grdctl rdp set-tls-key ~/.rdp-certs/grd-tls.key

**Comment by tmichett** [comment]
Restart Service 

systemctl --user restart gnome-remote-desktop.service

**Comment by tmichett** [comment]
https://extensions.gnome.org/extension/4338/allow-locked-remote-desktop/

**Comment by tmichett** [comment]
Per-user installations: ~/.local/share/gnome-shell/extensions/
System-wide installations: /usr/share/gnome-shell/extensions/ (you'll need administrator privileges to view this)

**Comment by tmichett** [comment]
Create script or playbook to do this work

**Comment by tmichett** [comment]
[kiosk@foundation0 ~]$ gnome-extensions enable ding@rastersoft.com
[kiosk@foundation0 ~]$ gnome-extensions enable allowlockedremotedesktop@kamens.us

**Comment by tmichett** [comment]
[kiosk@foundation0 ~]$ grdctl status
Overall:
	Unit status: active
RDP:
	Status: enabled
	Port: 3389
	TLS certificate: /home/kiosk/.rdp-certs/grd-tls.crt
	TLS fingerprint: 5a:16:b3:59:87:b4:a2:b1:e3:45:22:32:3d:4d:a6:28:b6:58:1a:22:10:df:03:b9:ba:71:ba:ee:4e:6b:73:0f
	TLS key: /home/kiosk/.rdp-certs/grd-tls.key
	View-only: no
	Negotiate port: yes
	Username: (hidden)
	Password: (hidden)

**Comment by tmichett** [comment]
Definitely need to set the credentials and create the certificate

**Comment by tmichett** [comment]
gnome-extensions list
gnome-extensions list --enabled

**Comment by tmichett** [comment]
fatal: [foundation0]: FAILED! => {"changed": true, "cmd": ["grdctl", "rdp", "set-credentials", "kiosk", "redhat"], "delta": "0:00:00.062402", "end": "2025-05-15 12:15:03.401615", "msg": "non-zero return code", "rc": 1, "start": "2025-05-15 12:15:03.339213", "stderr": "Cannot create an item in a locked collection", "stderr_lines": ["Cannot create an item in a locked collection"], "stdout": "", "stdout_lines": []}

**Comment by tmichett** [comment]
```
---
- name: Enable RDP on RHEL with GNOME and Wayland for RHEL10
  hosts: Instructor
  become: true
  tasks:

    - name: Install required packages for RDP
      yum:
        name:
          - gnome-remote-desktop
          - freerdp
        state: present

    - name: Allow RDP traffic through firewalld
      firewalld:
        port: 3389/tcp
        permanent: yes
        state: enabled
        immediate: yes

    - name: Configure RDP with GNOME settings
      command: gsettings set org.gnome.desktop.remote-desktop.rdp enable true
      become_user: kiosk

    - name: Set a password for RDP authentication
      command: gsettings set org.gnome.desktop.remote-desktop.rdp view-only false
      become_user: kiosk

    - name: Restart the GNOME remote desktop service
      systemd:
        name: gnome-remote-desktop.service
        state: restarted

- name: Setup for KIOSK User
  hosts: Instructor
  remote_user: kiosk
  become: false
  tasks:
    - name: Set a password for RDP authentication - GSettings
      command: gsettings set org.gnome.desktop.remote-desktop.rdp view-only false
    - name: Configure RDP with GNOME settings - GSettings
      command: gsettings set org.gnome.desktop.remote-desktop.rdp enable true
    - name: Set a password for RDP authentication - GSettings
      command: gsettings set org.gnome.desktop.remote-desktop.rdp view-only false
    - name: Configure RDP with GNOME settings - GSettings
      command: gsettings set org.gnome.desktop.remote-desktop.rdp enable true

### Enable GNOME Extension
## Need extension installed (https://extensions.gnome.org/extension/4338/allow-locked-remote-desktop/)
#    - name: Install Extension
#      command: unzip /home/kiosk/rhci-foundation/Ansible/Foundation/files/allowlockedremotedesktopkamens.us.v15.shell-extensionv47.zip -d ~/.local/share/gnome-shell/extensions/allowlockedremotedesktop@kamens.us


## Only runs after a reboot as the extension isn't recognize.
    - name: Enable GNOME Extension for Locked Remote Desktop user-level
      command: gnome-extensions enable allowlockedremotedesktop@kamens.us

### Setting UN/PW Again
    - name: Username and Password user-level
      command: grdctl rdp set-credentials kiosk redhat

- name: Restart RDP Service
  hosts: Instructor
  become: true
  tasks:

    - name: Restart the GNOME remote desktop service (configured)
      systemd:
        name: gnome-remote-desktop.service
        state: restarted
```
